# config.py

# Telegram Bot Token (Generated by @BotFather)
BOT_TOKEN = '8012075666:AAFXHElXnJNbVvPamfI57PDQ27vQ_ut0vv4'

# Your Telegram Chat ID (Get this from the /getUpdates API method)
CHAT_ID = '922582998'
